title: Radek Dymacz | AI & Automation Expert
description: Expert in AI, Machine Learning, Cloud Architecture, and Intelligent Automation. Specializing in AI agents, cloud solutions, and enterprise automation.
url: https://radekdymacz.github.io
author: Radek Dymacz
twitter:
  username: radekdymacz
  card: summary_large_image
social:
  name: Radek Dymacz
  links:
    - https://github.com/radekdymacz
    - https://linkedin.com/in/radekdymacz

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Google Analytics
google_analytics: # Add your Google Analytics ID here

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
