title: AI-Driven Automation
description: Empowering People with AI-Driven Automation and Expertise
url: "https://radekdymacz.github.io"
baseurl: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
