site_name: Radek Dymacz
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top

nav:
  - Home: index.md
  - Sketches: sketches.md
  - About: about.md

repo_url: https://github.com/radekdymacz
repo_name: radekdymacz

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
